# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
        migrations.CreateModel(
            name='Remetente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('ativo', models.BooleanField(default=True)),
                ('cpf', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_envio', models.DateTimeField(auto_now_add=True)),
                ('quantidade_de_emails', models.IntegerField()),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptor.Projetos')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptor.Remetente')),
            ],
            options={
                'verbose_name': 'Submiss\xe3o',
                'verbose_name_plural': 'Submiss\xf5es',
            },
        ),
        migrations.AddField(
            model_name='projetos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptor.Remetente'),
        ),
    ]
