# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='projeto',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
